### ISSUE TITLE
tiled_conv_dw wrong implementation

### ISSUE THREAD

**Issue by johnny-wang16** [ucb-bar/gemmini-rocc-tests#21]
the function `tiled_conv_dw` in gemmini.h produces wrong output. Seems like the input pointer is incorrectly updated. A simple test case like : input with shape 1x2x4x4 (Batch dim, Channel dim, H, W) depth-wise convolving with 1x2x3x3 kernel will show this.: ex
```
     // input 
    static elem_t cnn_convd_1_in[4*4][2] row_align(1) = {{{1,1},{0,1},{1,0},{1,0},
                                                         {0,0},{0,1},{0,0},{1,0},
                                                         {1,0},{0,1},{0,0},{1,0},
                                                         {1,0},{0,1},{0,0},{1,0}},;
     // weight 

    static const elem_t cnn_convd_1_w_flat[3*3][2] row_align(1) = {{1,1},{1,1},{1,1},
                                                                   {1,1},{1,1},{1,1},
                                                                   {1,1},{1,1},{1,1}};
```
PS: the CPU version (conv_dw) of this function is working correctly tho.

**Comment by fPecc** [comment]
Hi @johnny-wang16 , I found the same issue today, and have been trying to crack the problem for a while now. I think the problem might be in file gemmini.h, line 1659. The input pointer is not being modified by the function (the filter pointer seems to be correctly updated).

Edit: there is a pending merge which adds a test for the depthwise convolution and also changes some code in gemmini.h. I will look at it tomorrow.

**Comment by hngenc** [comment]
I think I've figured out the bug here.

I'm working on a solution in the `dw` branch. Hoping to have it finished by the end of next week.

**Comment by hngenc** [comment]
Depthwise convolutions should be working now in Gemmini's `dev` branch. You can look at the `conv_dw` test for an example of how to run depthwise convolutions.

Performance will not be great, which is partially due to the low arithmetic intensity of dw convs, but is also due to Gemmini's lack of optimization for dw convs. Dw conv performance can be improved in the future. Right now, it should be functionally correct at least, and will be faster than the CPU.

I'm closing the issue for now, but if you find that dw convs are still broken for you, then feel free to re-open it.
